import { expect, test } from '@playwright/test'

test('RSS starts minimal and disclosure preserves its trace and pause state', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('.led-tag')).toHaveCount(4)
  await page.getByRole('button', { name: 'Open RSS chart', exact: true }).click()
  const panel = page.getByRole('complementary', { name: 'RSS chart', exact: true })
  await expect(panel).toHaveClass(/compact/)
  await expect(panel.getByRole('list', { name: 'LED color legend' }).locator('li')).toHaveCount(4)
  await expect(panel.getByRole('button', { name: 'Pause RSS trace' })).toHaveCount(0)
  await expect(panel.getByRole('button', { name: 'Optical settings' })).toHaveCount(0)
  await expect(panel.locator('[data-ideal-power-w]')).toHaveCount(0)
  await panel.locator('.rss-chart-svg').evaluate((svg) => svg.setAttribute('data-original-svg', 'true'))
  await expect.poll(async () => Number(await panel.getAttribute('data-sample-count'))).toBeGreaterThan(3)
  await panel.getByRole('button', { name: 'Show RSS details' }).click()
  await expect(panel).toHaveClass(/expanded/)
  await expect(panel.locator('[data-ideal-power-w]')).toHaveCount(4)
  await panel.getByRole('button', { name: 'Pause RSS trace' }).click()
  const count = await panel.getAttribute('data-sample-count')
  const time = await panel.getAttribute('data-time')
  await panel.getByRole('button', { name: 'Hide RSS details' }).click()
  await expect(panel).toHaveClass(/compact/)
  await expect(panel.locator('[data-ideal-power-w]')).toHaveCount(0)
  await page.waitForTimeout(150)
  await panel.getByRole('button', { name: 'Show RSS details' }).click()
  await expect(panel.getByRole('button', { name: 'Resume RSS trace' })).toBeVisible()
  await expect(panel).toHaveAttribute('data-sample-count', count!)
  await expect(panel).toHaveAttribute('data-time', time!)
  await expect(panel.locator('.rss-chart-svg')).toHaveAttribute('data-original-svg', 'true')
})

test('X-Y plan uses equal world scale and shows real LED and receiver positions only', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('cambridge-digital-twin:v1', JSON.stringify({ room: { width: 6, depth: 3, height: 2.5 }, receiver: { position: [0.4, -0.2, 0.3] } })))
  await page.goto('/')
  await expect(page.locator('.receiver-tag')).toBeVisible()
  await expect(page.getByRole('complementary', { name: 'X-Y plan' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Open X-Y plan', exact: true }).click()
  const plan = page.getByRole('complementary', { name: 'X-Y plan' })
  await expect(plan.getByRole('img', { name: 'X-Y position map', exact: true })).toBeVisible()
  await expect(plan.locator('.plan-led-marker')).toHaveCount(4)
  await expect(plan.locator('.plan-estimate-marker')).toHaveCount(0)
  await expect(plan.getByRole('list', { name: 'Estimated positions' })).toHaveCount(0)
  const receiver = plan.locator('.plan-receiver-marker')
  await expect(receiver).toHaveAttribute('data-world-x', '0.4')
  await expect(receiver).toHaveAttribute('data-world-y', '-0.2')
  const width = Number(await plan.locator('.plan-room').getAttribute('width'))
  const height = Number(await plan.locator('.plan-room').getAttribute('height'))
  expect(width / height).toBeCloseTo(2)
  const lower = plan.locator('[data-led-id="LED-01"]')
  const upper = plan.locator('[data-led-id="LED-03"]')
  expect(Number(await lower.getAttribute('data-world-y'))).toBeLessThan(Number(await upper.getAttribute('data-world-y')))
  expect(Number(await lower.locator('circle').getAttribute('cy'))).toBeGreaterThan(Number(await upper.locator('circle').getAttribute('cy')))
  await page.getByRole('button', { name: 'Open settings', exact: true }).click()
  await page.getByRole('tab', { name: 'Receiver', exact: true }).click()
  for (const [axis, value] of [['X', '-0.7'], ['Y', '0.4'], ['Z', '0.6']]) {
    const input = page.getByRole('spinbutton', { name: `Receiver position · ${axis} value`, exact: true })
    await input.fill(value)
    await input.press('Enter')
  }
  await expect(receiver).toHaveAttribute('data-world-x', '-0.7')
  await expect(receiver).toHaveAttribute('data-world-y', '0.4')
  await expect(receiver).toHaveAttribute('data-world-z', '0.6')
  await page.getByRole('button', { name: 'Close configuration panel' }).click()
  await plan.getByRole('button', { name: 'Close X-Y plan' }).click()
  await expect(page.getByRole('button', { name: 'Open X-Y plan', exact: true })).toBeFocused()
})

for (const viewport of [{ width: 1440, height: 1000 }, { width: 390, height: 844 }, { width: 844, height: 390 }]) {
  test(`analysis windows stay separate and scroll-reachable at ${viewport.width}x${viewport.height}`, async ({ page }) => {
    await page.setViewportSize(viewport)
    await page.goto('/')
    await expect(page.locator('.receiver-tag')).toBeVisible()
    await page.locator('canvas').evaluate((canvas) => canvas.setAttribute('data-original-canvas', 'true'))
    await page.getByRole('button', { name: 'Open RSS chart', exact: true }).click()
    await page.getByRole('button', { name: 'Open X-Y plan', exact: true }).click()
    const plan = page.getByRole('complementary', { name: 'X-Y plan' })
    const rss = page.getByRole('complementary', { name: 'RSS chart' })
    const planBox = (await plan.boundingBox())!
    const rssBox = (await rss.boundingBox())!
    expect(rssBox.y).toBeGreaterThanOrEqual(planBox.y + planBox.height + 10)
    await rss.getByRole('button', { name: 'Show RSS details' }).click()
    await expect(rss.getByRole('button', { name: 'Pause RSS trace' })).toBeVisible()
    await rss.getByRole('button', { name: 'Close RSS chart' }).click()
    await plan.getByRole('button', { name: 'Close X-Y plan' }).click()
    await expect(page.locator('canvas')).toHaveAttribute('data-original-canvas', 'true')
    expect(await page.locator('canvas').boundingBox()).toEqual({ x: 0, y: 0, ...viewport })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  })
}
