function s = gob_error_summary(truth,estimates)
delta = estimates-truth; errors = vecnorm(delta); count = numel(errors);
phat = mean(errors>.1); z = 1.95996398454; denominator = 1+z^2/count;
center = (phat+z^2/(2*count))/denominator;
radius = z*sqrt(phat*(1-phat)/count+z^2/(4*count^2))/denominator;
s = struct('count',count,'median_m',gob_quantile(errors,.5),'p95_m',gob_quantile(errors,.95), ...
    'max_m',max(errors),'rmse_m',sqrt(mean(errors.^2)), ...
    'rmse_x_m',sqrt(mean(delta(1,:).^2)),'rmse_y_m',sqrt(mean(delta(2,:).^2)), ...
    'rmse_z_m',sqrt(mean(delta(3,:).^2)),'fraction_error_1cm',mean(errors<.01), ...
    'fraction_error_10cm',mean(errors<.1),'failure_10cm_wilson95_low',max(0,center-radius), ...
    'failure_10cm_wilson95_high',min(1,center+radius));
end
