% Parametro Fijos del experimento

testbed = struct( ... % testbed
  'x',          [-1.5 1.5], ...
  'y',          [-1.5 1.5], ...
  'z',          [0 2.5], ...
  'gridstep',   0.1 ...
);

UE = struct( ... % User Equipment
  'id',          "PD1", ...
  'delta_tilt',  10,...                  % INCERTIDUMBRE de la orientacion
  'pos',         [0 0 0.75], ...         % altura del móvil/plano de prueba
  'n_r'  ,       [0 0 1], ...            % PD mira hacia +z (al techo)
  'A_det',       (2.65e-3)*(2.65e-3), ...               % área activa
  'FOV_deg',     68, ...                 % campo de visión (semiángulo)
  'Ts',          1.0, ...                % ganancia del filtro óptico
  'g_ri',        1.0, ...                % ganancia concentrador (si no hay, =1)
  'R_pd',        0.62, ...                % Responsivity
  'label',       "BPX61" ...
);

channel = struct( ...
  'sigma2',      30e6*10^(-23.0), ...
  'model',      'lambertian'...
);

% ===========================================
% Multi-LED / Config: 4-Sources
% ===========================================
AP_multi_fixed_LED = struct( ...
  'id',             {"AP1","AP2","AP3","AP4"}, ...
  'pos',            { [-0.75 0.75 2.5], [0.75 0.75 2.5], [-0.75 -0.75 2.5], [0.75 -0.75 2.5] }, ...
  'n_t',            { [0 0 -1], [0 0 -1], [0 0 -1], [0 0 -1]}, ...
  'set_n_t',        { [0 0 -1], [0 0 -1], [0 0 -1], [0 0 -1]}, ...
  'P_t',            { 0.405, 0.405, 0.405, 0.405 }, ... % Optical Power [W]
  'theta_half',     { 45, 45, 45, 45 }, ...
  'm',              { 2, 2, 2, 2}, ...
  'label',          {"LZ1-R702","LZ1-R702","LZ1-R702","LZ1-R702"} ...
);

%  'set_n_t',        [20 0; 20 120; 20 240], ...
%  'set_n_t',        [14 135; 70 103; 70 167], ... % Opt [-1.5 0 0 1.5]
% ===========================================
% Beam-steering Single-LED / Config: 1-Source
% ===========================================
AP_one_beamsteering_LED = struct( ...
  'id',             "AP1", ...
  'pos',            [0 0 2.5], ...
  'n_t',            [0 0 -1], ...
  'set_n_t',        [20 0; 20 120; 20 240], ...
  'P_t',            0.405, ...
  'theta_half',     45, ...
  'm',              2, ...
  'label',          "LZ1-R702" ...
);

% ===========================================
% Beam-steering Single-LED / Config: 2-Source
% ===========================================
AP_two_beamsteering_LED  = struct( ...
  'id',             { "AP1", "AP2"}, ...
  'pos',            { [-0.75 0 2.5], [0.75 0 2.5] }, ...
  'n_t',            { [0 0 -1], [0 0 -1] }, ...
  'P_t',            { 0.405, 0.405}, ...
  'set_n_t',        { [20 0; 20 120; 20 240], [20 0; 20 120; 20 240] }, ...
  'theta_half',     { 45, 45 }, ...
  'm',              { 2, 2}, ...
  'label',          { "LZ1-R702", "LZ1-R702"} ...
);


AP_config = struct( ...
  'multi_fixed_LED', AP_multi_fixed_LED, ...
  'one_beamsteering_LED', AP_one_beamsteering_LED, ...
  'two_beamsteering_LED', AP_two_beamsteering_LED ...
);

% Function 
angles2vec = @(ang_deg) ...
    [ sind(ang_deg(:,1)).*cosd(ang_deg(:,2)), ...
      sind(ang_deg(:,1)).*sind(ang_deg(:,2)), ...
     -cosd(ang_deg(:,1))                      ];

disp('VLP definitions and parameters loaded successfully')