function summary = rx_design_summary(r)
b = r.best;
summary = table([b.half_angle_deg]', [b.fov_deg]', [b.cone_tilt_deg]', [b.K_minimum_peb]', ...
    [b.K_recommended]', [b.K_fixed_budget_minimum]', ...
    100*arrayfun(@(x) x.refinement.cone_rms_m, b)', 100*arrayfun(@(x) x.metrics.rms_full_m, b)', ...
    100*arrayfun(@(x) x.validation_metrics.coverage, b)', 100*arrayfun(@(x) x.validation_metrics.rms_full_m, b)', ...
    [b.area_minimum_peb_mm2]', [b.area_target_mm2]', 100*[b.area_minimum_rms_m]', ...
    'VariableNames', {'HalfAngle_deg', 'FOV_deg', 'ConeTilt_deg', 'K_minPEB', 'K_recommended', 'K_fixedBudget', ...
    'ConeRMS_cm', 'RefinedRMS_cm', 'ValidationCoverage_percent', 'ValidationRMS_cm', ...
    'Area_minPEB_mm2', 'Area_target_mm2', 'Area_minRMS_cm'});
end
