function d = gob_diagnostics(m)
c = m.config; q = m.local_q(13,:);
d = struct('focal_mm',1000*c.radii/(c.index-1), ...
    'optical_power_diopters',(c.index-1)./c.radii, ...
    'center_thickness_mm',1000*m.center_thicknesses, ...
    'max_clipping_upper_bound',max(m.clipping_bounds,[],'all'), ...
    'max_chief_ray_tilt_deg',max(acosd(max(-1,min(1,-m.directions(3,:))))), ...
    'min_virtual_waist_distance_mm',1000*min(real(m.q)), ...
    'min_output_rayleigh_range_mm',1000*min(imag(m.q)), ...
    'center_beam_radius_at_3m_mm',1000*sqrt(c.wavelength/pi*abs(q+3).^2./imag(q)));
end
